function vcu_create_model2()
%VCU_CREATE_MODEL2 Create models/VCU_M2.slx (full simplified VCU).
%   Layout: left-to-right grid, generous spacing, orthogonal autorouting.
%   Stateflow 3-state (Start/Drive/Brake) with actions in state entry (en:).

    projdir = fileparts(fileparts(mfilename('fullpath')));
    ioc     = fullfile(projdir,'00_HW','F103C8T6','VCU_F103.ioc');
    m       = 'VCU_M2';
    slx     = fullfile(projdir,'models',[m '.slx']);

    if bdIsLoaded(m), close_system(m,0); end
    if isfile(slx), delete(slx); end

    new_system(m);
    load_system('stm32blockslib');
    blks = find_system('stm32blockslib','SearchDepth',1,'Type','Block');
    pick = @(kw) blks{find(contains(blks,kw),1)};

    set_param(m,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
        'FixedStep','0.0005','StopTime','inf','SystemTargetFile','ert.tlc');

    % ---- STM32 peripheral blocks ----
    add_block(pick('Analog to Digital'), [m '/ADC'],          'Position',gpos(1,1,240,160));
    add_block(pick('CAN Write'),          [m '/CAN_TX_0x100'],'Position',gpos(5,1,240,160));
    add_block(pick('CAN Write'),          [m '/CAN_TX_0x500'],'Position',gpos(5,2,240,160));
    add_block(pick('CAN Write'),          [m '/CAN_TX_0x600'],'Position',gpos(5,3,240,160));
    add_block(pick('CAN Read'),           [m '/CAN_RX_0x200'],'Position',gpos(1,2,240,160));
    add_block(pick('USART Write'),        [m '/UART_DBG'],    'Position',gpos(6,3,240,160));
    add_block(pick('PWM Output'),         [m '/BUZZER'],      'Position',gpos(5,4,240,160));
    add_block(pick('Digital Port Write'), [m '/Heartbeat'],   'Position',gpos(2,3,240,160));
    add_block('simulink/Sources/Pulse Generator',[m '/HB'],   'Position',gpos(1,3,120,80));
    add_block('simulink/Sources/Constant',[m '/DUTY50'],      'Position',gpos(4,4,120,80));

    % ---- MATLAB Function blocks ----
    mf = 'simulink/User-Defined Functions/MATLAB Function';
    add_block(mf,[m '/scale_fp'], 'Position',gpos(2,1,240,140));
    add_block(mf,[m '/ctrl_fp'],  'Position',gpos(3,1,240,140));
    add_block(mf,[m '/pack_tq'],  'Position',gpos(4,1,240,140));
    add_block(mf,[m '/pack_st'],  'Position',gpos(4,2,240,140));
    add_block(mf,[m '/rx_dispatch'],'Position',gpos(2,2,240,140));
    add_block(mf,[m '/pack_dbg'], 'Position',gpos(4,3,240,140));

    % ---- Stateflow chart ----
    add_block('sflib/Chart',[m '/state_chart'],'Position',gpos(3,2,300,240));

    % ---- Configure peripheral blocks ----
    set_param([m '/ADC'],'ADCModule','ADC1','ConversionGroup','Regular', ...
        'TriggerMode','Trigger and read','NumberOfConversions','8');
    set_param([m '/CAN_TX_0x100'],'CANModule','CAN1','DataFormatWriteMode','Raw data', ...
        'IdentifierVia','Dialog','Identifier','256','IdentifierType','Standard (11-bit identifier)', ...
        'DataLengthVia','Dialog','DataLength','8');
    set_param([m '/CAN_TX_0x500'],'CANModule','CAN1','DataFormatWriteMode','Raw data', ...
        'IdentifierVia','Dialog','Identifier','1280','IdentifierType','Standard (11-bit identifier)', ...
        'DataLengthVia','Dialog','DataLength','8');
    set_param([m '/CAN_TX_0x600'],'CANModule','CAN1','DataFormatWriteMode','Raw data', ...
        'IdentifierVia','Dialog','Identifier','1536','IdentifierType','Standard (11-bit identifier)', ...
        'DataLengthVia','Dialog','DataLength','8');
    set_param([m '/CAN_RX_0x200'],'CANModule','CAN1','ReadSource','FIFO 0', ...
        'OperationReadMode','Data','OutputTypeReadMode','Unpacked');
    set_param([m '/UART_DBG'],'UARTModule','USART1');
    set_param([m '/BUZZER'],'TimerModule','TIM1','DutycycleUnits','Percentage', ...
        'EnableChannel1','on','EnableChannel2','off','EnableChannel3','off', ...
        'EnableChannel4','off','EnableChannel5','off','EnableChannel6','off', ...
        'EnableFrequencyInput','off');
    set_param([m '/DUTY50'],'Value','50');
    set_param([m '/Heartbeat'],'PortName','GPIOC','PinNumber','[13]','ReadOperation','off','IOAsArray','on');
    set_param([m '/HB'],'Amplitude','1','Period','2','PulseWidth','50','SampleTime','0.0005');

    % ---- MATLAB Function code ----
    setEmScript(m,'/scale_fp', [ ...
        "function [v_mV, throttle, brake] = vcu_scale(adc)" newline ...
        "%#codegen" newline ...
        "v_mV = fi(zeros(8,1),1,16,0);" newline ...
        "k = fi(3300/4095,1,16,15);" newline ...
        "for i = 1:8" newline ...
        "    v_mV(i) = fi(adc(i),1,16,0)*k;" newline ...
        "end" newline ...
        "throttle = v_mV(1);" newline ...
        "brake = v_mV(3);" newline ...
        "end"]);
    setEmScript(m,'/ctrl_fp', [ ...
        "function torque = vcu_ctrl(v_mV, vx_meas, state)" newline ...
        "%#codegen" newline ...
        "persistent vx_est" newline ...
        "if isempty(vx_est)" newline ...
        "    vx_est = int16(0);" newline ...
        "end" newline ...
        "vx_est = vx_est + int16(0.3*(double(vx_meas)-double(vx_est)));" newline ...
        "torque = int16(zeros(4,1));" newline ...
        "if state == 1" newline ...
        "    b = v_mV(1);" newline ...
        "    torque(1)=b; torque(2)=b; torque(3)=b; torque(4)=b;" newline ...
        "elseif state == 3" newline ...
        "    b = v_mV(3);" newline ...
        "    torque(1)=-b; torque(2)=-b; torque(3)=-b; torque(4)=-b;" newline ...
        "end" newline ...
        "end"]);
    setEmScript(m,'/pack_tq', [ ...
        "function d = vcu_pack_tq(tq)" newline ...
        "%#codegen" newline ...
        "d = zeros(8,1,'uint8');" newline ...
        "for i=1:4" newline ...
        "    u = uint16(tq(i));" newline ...
        "    d(2*i-1) = uint8(bitshift(u,-8));" newline ...
        "    d(2*i)   = uint8(bitand(u,255));" newline ...
        "end" newline ...
        "end"]);
    setEmScript(m,'/pack_st', [ ...
        "function d = vcu_pack_st(v_mV, state)" newline ...
        "%#codegen" newline ...
        "d = zeros(8,1,'uint8');" newline ...
        "d(1) = uint8(state);" newline ...
        "for i=1:3" newline ...
        "    u = uint16(v_mV(i));" newline ...
        "    d(2*i) = uint8(bitshift(u,-8));" newline ...
        "    d(2*i+1) = uint8(bitand(u,255));" newline ...
        "end" newline ...
        "end"]);
    setEmScript(m,'/rx_dispatch', [ ...
        "function [vx, bms, sens] = vcu_rx(Data, Id)" newline ...
        "%#codegen" newline ...
        "vx = int16(0); bms = int16(0); sens = int16(0);" newline ...
        "if Id == uint32(512)" newline ...
        "    vx = int16(bitshift(uint16(Data(1)),8) + uint16(Data(2)));" newline ...
        "elseif Id == uint32(768)" newline ...
        "    bms = int16(bitshift(uint16(Data(1)),8) + uint16(Data(2)));" newline ...
        "elseif Id == uint32(1024)" newline ...
        "    sens = int16(bitshift(uint16(Data(1)),8) + uint16(Data(2)));" newline ...
        "end" newline ...
        "end"]);
    setEmScript(m,'/pack_dbg', [ ...
        "function d = vcu_dbg(state, vx, throttle)" newline ...
        "%#codegen" newline ...
        "d = zeros(8,1,'uint8');" newline ...
        "d(1)=uint8(state);" newline ...
        "u=uint16(vx); d(2)=uint8(bitshift(u,-8)); d(3)=uint8(bitand(u,255));" newline ...
        "u=uint16(throttle); d(4)=uint8(bitshift(u,-8)); d(5)=uint8(bitand(u,255));" newline ...
        "end"]);

    % ---- Stateflow chart ----
    buildStateflowChart(m,'/state_chart');

    % ---- Wiring (orthogonal autorouting) ----
    al(m,'ADC/1','scale_fp/1');
    al(m,'scale_fp/1','ctrl_fp/1');
    al(m,'CAN_RX_0x200/1','rx_dispatch/1');
    al(m,'CAN_RX_0x200/3','rx_dispatch/2');
    al(m,'rx_dispatch/1','ctrl_fp/2');
    al(m,'state_chart/1','ctrl_fp/3');
    al(m,'scale_fp/2','state_chart/1');
    al(m,'scale_fp/3','state_chart/2');
    al(m,'ctrl_fp/1','pack_tq/1');
    al(m,'pack_tq/1','CAN_TX_0x100/1');
    al(m,'scale_fp/1','pack_st/1');
    al(m,'state_chart/1','pack_st/2');
    al(m,'pack_st/1','CAN_TX_0x500/1');
    al(m,'state_chart/1','pack_dbg/1');
    al(m,'rx_dispatch/1','pack_dbg/2');
    al(m,'scale_fp/2','pack_dbg/3');
    al(m,'pack_dbg/1','UART_DBG/1');
    al(m,'pack_dbg/1','CAN_TX_0x600/1');
    al(m,'DUTY50/1','BUZZER/1');
    al(m,'HB/1','Heartbeat/1');

    % ---- Target configuration ----
    set_param(m,'HardwareBoard','STM32F1xx Based');
    set_param(m,'Toolchain','GNU Tools for STM32');
    codertarget.data.setParameterValue(m,'STM32CubeMX.ProjectFile',ioc);
    codertarget.data.setParameterValue(m,'STM32CubeMX.DeviceId','STM32F103C8Tx');
    codertarget.data.setParameterValue(m,'STM32CubeMX.Family','STM32F1');
    codertarget.data.setParameterValue(m,'Runtime.BuildAction','Build, load and run');
    codertarget.data.setParameterValue(m,'STM32CubeMX.ConnectivityMode','st-link');
    codertarget.data.setParameterValue(m,'STM32CubeMX.ConnectionPort','SWD');
    codertarget.data.setParameterValue(m,'STM32CubeMX.Frequency','4000');
    codertarget.data.setParameterValue(m,'STM32CubeMX.Mode','Normal');
    codertarget.data.setParameterValue(m,'STM32CubeMX.ResetMode','Software reset');
    codertarget.data.setParameterValue(m,'STM32CubeMX.AutoDetectBoard',1);

    save_system(m,slx);
    fprintf('Saved %s\n', slx);
    close_system(m,0);
end

function p = gpos(col,row,w,h)
    % Grid position (left->right). Generous spacing.
    W=240; H=160; SX=100; SY=120;
    x = 40 + (col-1)*(W+SX);
    y = 40 + (row-1)*(H+SY);
    p = [x y x+w y+h];
end

function setEmScript(model, blkPath, script)
    rt = sfroot;
    ch = rt.find('-isa','Stateflow.EMChart','-and','Path',[model blkPath]);
    if isempty(ch)
        error('EMChart not found: %s%s', model, blkPath);
    end
    if isstring(script)
        script = char(join(script,""));
    end
    ch.Script = script;
end

function buildStateflowChart(model, blkPath)
    rt = sfroot;
    ch = rt.find('-isa','Stateflow.Chart','-and','Path',[model blkPath]);
    if isempty(ch)
        error('Chart not found: %s%s', model, blkPath);
    end
    delete(ch.find('-isa','Stateflow.State'));
    delete(ch.find('-isa','Stateflow.Transition'));

    % Data ports
    u1 = Stateflow.Data(ch); u1.Name='throttle'; u1.Scope='Input';  u1.DataType='int16';
    u2 = Stateflow.Data(ch); u2.Name='brake';    u2.Scope='Input';  u2.DataType='int16';
    u3 = Stateflow.Data(ch); u3.Name='speed';    u3.Scope='Input';  u3.DataType='int16';
    y1 = Stateflow.Data(ch); y1.Name='state';    y1.Scope='Output'; y1.DataType='uint8';

    % States (large boxes, generous spacing). Actions live in state entry (en:).
    s1 = Stateflow.State(ch); s1.Name='Start';
    s1.LabelString = sprintf('Start\nen: state = uint8(0);');
    s1.Position=[40 80 240 120];
    s2 = Stateflow.State(ch); s2.Name='Drive';
    s2.LabelString = sprintf('Drive\nen: state = uint8(1);');
    s2.Position=[400 80 240 120];
    s3 = Stateflow.State(ch); s3.Name='Brake';
    s3.LabelString = sprintf('Brake\nen: state = uint8(3);');
    s3.Position=[760 80 240 120];

    t0 = Stateflow.Transition(ch); t0.Destination = s1;

    t12 = Stateflow.Transition(ch); t12.Source=s1; t12.Destination=s2;
    t12.LabelString = '[throttle > 50]';
    t21 = Stateflow.Transition(ch); t21.Source=s2; t21.Destination=s1;
    t21.LabelString = '[throttle <= 50 && speed <= 0]';
    t23 = Stateflow.Transition(ch); t23.Source=s2; t23.Destination=s3;
    t23.LabelString = '[brake > 50]';
    t32 = Stateflow.Transition(ch); t32.Source=s3; t32.Destination=s2;
    t32.LabelString = '[brake <= 50 && throttle > 50]';
    t31 = Stateflow.Transition(ch); t31.Source=s3; t31.Destination=s1;
    t31.LabelString = '[speed <= 0 && throttle <= 50]';
end

function al(m,a,b)
    % Add line with orthogonal (right-angle) autorouting.
    add_line(m,a,b,'autorouting','on');
end
